site_name: AfriSenti SemEval
site_url: https://example.com/
theme:
    name: mkdocs
nav:
    - Home: index.md
    - Participation: participation.md
    - Resources: Resources.md
    - Organizers: organizer.md
