site_name: AfriSenti SemEval
site_url: https://example.com/
theme:
    name: mkdocs
nav:
    - Home: index.md
    - Participation: participation.md
    - Baselines: baselines.md
    - Paper Instructions: paper.md
    - Organizers: organizer.md
